
@baseURL=https://secure.snd.payu.com
@authToken=34608647-9a02-4327-88d3-c896d4820888

###
POST {{baseURL}}/pl/standard/user/oauth/authorize 
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id=461693
&client_secret=a952180129fa77075f629a4e65d9419e

###
GET {{baseURL}}/api/v2_1/paymethods
Authorization: Bearer {{authToken}}

###
## create order
##
POST {{baseURL}}/api/v2_1/orders
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "notifyUrl":"https://your.eshop.com/notify",
    "customerIp":"127.0.0.1",
    "merchantPosId":"461693",
    "recurring": "FIRST",
    "description":"Laptop",
    "currencyCode":"PLN",
    "totalAmount":"15000",
    "extOrderId":"n7kln2ipw5q1neabmjabc123",
    "products":[
        {
            "name":"Laptop",
            "unitPrice":"15000",
            "quantity":"1"
        }
    ],
    "buyer": {
        "email": "john.doe@example.com",
        "firstName": "John",
        "lastName": "Doe",
        "language": "en"
    },                         
    "payMethods": {
        "payMethod": {
            "value": "TOK_1KPKOR9GOPTT2IA0b8Qtgp4tJU8F",
            "type": "CARD_TOKEN"
        }
    }
}

###
## call notify on localhost
##
POST http://localhost:5275/notifypayment/asdf
Content-Type: application/json
PayU-Processing-Time: 1000                                     
Content-Type: application/json;charset=UTF-8
User-Agent: Jakarta Commons-HttpClient/3.1
Content-Length: 100
Authorization: Basic MTIzNDU2Nzg6QUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVo=
OpenPayu-Signature: sender=checkout;signature=d47d8a771d558c29285887febddd9327;algorithm=MD5;content=DOCUMENT
X-OpenPayU-Signature: sender=checkout;signature=d47d8a771d558c29285887febddd9327;algorithm=MD5;content=DOCUMENT
              
{ 
   "order":{ 
      "orderId":"LDLW5N7MF4140324GUEST000P01", 
      "extOrderId":"Id zamówienia w Twoim sklepie", 
      "orderCreateDate":"2012-12-31T12:00:00", 
      "notifyUrl":"http://tempuri.org/notify", 
      "customerIp":"127.0.0.1", 
      "merchantPosId":"{Id punktu płatności (pos_id)}", 
      "description":"Twój opis zamówienia", 
      "currencyCode":"PLN", 
      "totalAmount":"200", 
      "buyer":{ 
         "email":"john.doe@example.org", 
         "phone":"111111111", 
         "firstName":"John", 
         "lastName":"Doe",
         "language":"pl"
      },
      "payMethod": {
         "type": "PBL" //lub "CARD_TOKEN", "INSTALLMENTS"
      },
      "products":[
         { 
               "name":"Product 1", 
               "unitPrice":"200", 
               "quantity":"1" 
         }
      ], 
      "status":"COMPLETED" 
   },
   "localReceiptDateTime": "2016-03-02T12:58:14.828+01:00",
   "properties": [
      {
         "name": "PAYMENT_ID",
         "value": "151471228"
      }
   ]
}